### ISSUE TITLE
Title of HTML page is not updated anymore in 3.0

### ISSUE THREAD

**Issue by kelson42** [openzim/youtube#298] opened 2024-08-21 17:09 UTC
All the pages have the same title, see:
<img width="1080" alt="image" src="https://github.com/user-attachments/assets/d35dccd1-0581-4f81-aa2e-8d8a2b31c0c5">

**Comment by dan-niles** [comment] 2024-08-22 03:49
Should the page title include only the video title (e.g., `Les Délires de Maisons de Milliardaires !`), or should it also include the ZIM title (e.g., `Astrolabe | Les Délires de Maisons de Milliardaires !`)?

**Comment by kelson42** [comment] 2024-08-22 04:15
@dan-niles At this stage, I would do it like it was before, so only the video title. Same for playlist page, etc...

**Comment by benoit74** [comment] 2024-09-02 13:25
This is not really a regression but an intended change, discussed in https://github.com/openzim/youtube/issues/227

The reason behind it is that we know have one single HTML entry. And the content is dynamically updated with JS. We could hence also update the title dynamically from JS (this is the PR). I tried and failed in kolibri (but maybe my code was different, I do not recall). As far as I remember, some readers where not detecting the dynamic change of document title at all (not really a problem but a waste of code/energy) and some other readers (kiwix-serve if I'm not mistaken) where mixing up titles in browser history: looked like page N had the title of page N-1 in history.

**Comment by benoit74** [comment] 2024-09-02 13:25
I did not intended to close this issue at all, sorry, missclick.

**Comment by benoit74** [comment] 2024-09-02 13:26
I will test the ZIM built in the PR and revert.

**Closed** 2024-09-02 14:19 UTC
Labels: bug

**Comment by benoit74** [comment] 2024-09-02 14:23
As mentioned in https://github.com/openzim/youtube/pull/300#pullrequestreview-2275771129, I did not experienced again the issues I experienced with Kolibri. I'm probably not as a good frontend dev as @dan-niles ^^ Glad it works as expected.
