### ISSUE TITLE
VOA_learning_en_all fails repeatedly

### ISSUE THREAD

**Issue by Popolechien** [openzim/youtube#353] opened 2024-10-07 14:40 UTC
See https://farm.openzim.org/recipes/voa_learning_en_all and last run at https://farm.openzim.org/pipeline/9261aa3f-a8c8-4113-bbbd-9700aace9e9f/debug

Error message is `too many videos failed to download`, much like in #351

**Comment by benoit74** [comment] 2024-10-07 19:32
Duplicate of #351

**Closed by benoit74** 2024-10-07 19:32 UTC
Labels: bug
