### ISSUE TITLE
kiwix-serve search is broken when video title contains an apostrophe, with TED-Ed ZIM file

### ISSUE THREAD

**Issue by holta** [openzim/youtube#143] opened 2021-03-05 21:57 UTC
Summary:
- Title search (via search box's autocomplete) _does not_ work for such videos.
- FT (full-text) search _does work_ for such videos.

Example: https://youtu.be/dcZ0BXJYlUA is a video that is a part of the latest Kiwix TED-Ed ZIM file ([teded_en_all_2021-01.zim](http://download.kiwix.org/zim/ted/teded_en_all_2021-01.zim), published 2021-01-16) as can be seen here:
http://iiab.me/kiwix/teded_en_all_2021-01/A/building_the_world_s_largest_and_most_controversial_power_plant_alex_gendler.html

Recap &mdash; users cannot search for the above video, because even after it appears in the search box's autocomplete, as follows:

```
Building the world's largest (and most controversial) power plant - Alex Gendler
```

But then when you try to click it, the apostophe is expanded as follows:

```
Building the world&apos;s largest (and most controversial) power plant - Alex Gendler
```

FYI/Context: the very latest kiwix-serve 3.1.2-4 is in use on the above-mentioned server: http://iiab.me/kiwix/teded_en_all_2021-01/

PS please move this ticket to another repo if it belongs elsewhere.  Thank you.

**Comment by kelson42** [comment] 2021-03-06 05:48
@holta Might that be a duplicate of https://github.com/kiwix/kiwix-lib/issues/398 ?

**Comment by holta** [comment] 2021-03-06 11:22
@kelson42 that's really great news if PR https://github.com/kiwix/kiwix-lib/pull/458 might have fixed this just 2 days ago.

To allow for testing: will a new build of kiwix-tools (incl kiwix-serve) be published to http://download.kiwix.org/release/kiwix-tools/ including this change?

**Comment by kelson42** [comment] 2021-03-06 11:23
@holta Would you be able to give a try to http://download.kiwix.org/nightly/2021-03-06/ ?

**Comment by holta** [comment] 2021-03-06 16:46
It's likely fixed by http://download.kiwix.org/nightly/2021-03-06/ that I tested using http://iiab.me/kiwix/teded_en_all_2021-01/

Caveat: occasionally the search box still displayed a few of the following: (after clearing Chrome browser's cache, before relaunching the browser)

```
Building the world&apos;s largest (and most controversial) power plant - Alex Gendler
```
```
containing &apos;STRING-YOU-JUST-TYPED&apos;...
```

(Possibly the Chrome browser is not fully clearing its cache for ages still residual in memory.)

**Comment by holta** [comment] 2021-03-06 17:25
> At some point in the next weeks a new build/release will be published.

Great news.  FYI the new release of kiwix-tools would appear to be 45% larger (100MB instead of 69MB) which is fine, but what are the reasons if you have a moment?

Or if you don't have time, ideally its new functionality/changes can be summarized here?
https://github.com/kiwix/kiwix-tools/blob/master/Changelog

PS Feel free to close this issue as fixed and resolved.  As the above-mentioned intermittent glitches appear to have been transient as a result of the Chrome browser retaining stuff in memory (clearing a browser's cache is not quite enough!)

**Closed** 2021-03-06 17:54 UTC
Labels: bug, question
