### ISSUE TITLE
Scraper does not pull full description for top video in playlist

### ISSUE THREAD

**Issue by Popolechien** [openzim/youtube#108] opened 2020-06-24 07:54 UTC
I ran a scraper on https://www.youtube.com/playlist?list=PLr5n3ojAJWjRiuPrUAAveWrrqnNPPNzYK
The full zim is [here](http://download.kiwix.org/zim/other/aimhi_en_philosophy_2020-06.zim)
As far as I can tell it all went fine, except that the description of the first video (the one that appears on top) seems truncated

![Screenshot 2020-06-24 at 09 52 35](https://user-images.githubusercontent.com/21675885/85518394-79539f00-b600-11ea-90c5-d269ac427ae2.png)

This is not the case for the other videos, which have a similar text.

**Comment by rgaudin** [comment] 2020-06-24 08:01
Well it's not a bug, this has been changed in late April as we have no control over the length of this description so it was decided to truncate it to 200 characters. That's only for the homepage, you can still click on the title and access the article page of this video with the full description and the released date.

Closing this ; reopen if you want a change to this.

**Closed by rgaudin** 2020-06-24 08:01 UTC
Labels: bug

**Comment by Popolechien** [comment] 2020-06-24 08:06
okie dokie. Good enough atm.
