### ISSUE TITLE
Using non-latin script may cause crash?

### ISSUE THREAD

**Issue by Popolechien** [openzim/youtube#157] opened 2022-07-30 08:10 UTC
Creating a zim file (https://farm.openzim.org/recipes/avanti-units-and-measurements_hin/edit) I get the following error
`ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/usr/local/lib/python3.8/site-packages/MarkupSafe-2.1.1-py3.8-linux-x86_64.egg/markupsafe/__init__.py)`

Could it be due to the fact that the decscription uses hindi?

**Comment by kelson42** [comment] 2022-07-30 08:15
Duplicate of #156

**Closed** 2022-07-30 08:20 UTC
Labels: bug, duplicate, question
