### ISSUE TITLE
Succesful run… but no zim created

### ISSUE THREAD

**Issue by kelson42** [openzim/youtube#173] opened 2023-03-06 18:24 UTC
https://farm.openzim.org/pipeline/6f9f5c43643dfbf52d7c5046

Too me we should have a error if no zim is created.

**Comment by rgaudin** [comment] 2023-03-06 19:07
Duplicate of another ticket. ZIM files were created but the recipe did not request files to end with .zim

I think we have a ticket on zimfarm to enforce this.

**Closed** 2023-03-06 19:07 UTC
Labels: question

**Comment by kelson42** [comment] 2023-03-07 05:11
@rgaudin had forgotten about the rationals behind the symptom. I have fixed the recipe.
