### ISSUE TITLE
OER recipe failing

### ISSUE THREAD

**Issue by Popolechien** [openzim/youtube#350] opened 2024-10-07 14:30 UTC
I ran the [OER4schools](https://farm.openzim.org/recipes/oer4schools) recipe today and it failed with error seems to be `list index out of range`

The last successful run was 2 months ago (before the new skin).

**Comment by benoit74** [comment] 2024-10-07 19:34
This is a duplicate of https://github.com/openzim/youtube/issues/340, already solved in dev but not released.

**Closed by benoit74** 2024-10-07 19:34 UTC
Labels: bug
