### ISSUE TITLE
Channel recipe fails

### ISSUE THREAD

**Issue by Popolechien** [openzim/youtube#352] opened 2024-10-07 14:38 UTC
Recipe is at https://farm.openzim.org/recipes/telmidtice1_ar_all

Seems to return invalid channel ID

**Comment by benoit74** [comment] 2024-10-07 18:33
This is a duplicate of https://github.com/openzim/youtube/issues/340, already solved in dev but not released.

**Closed by benoit74** 2024-10-07 18:33 UTC
Labels: bug
